# -*- coding: utf-8 -*-
"""drawing with mouse .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_PytscylZ1BSO0v74XF6ZCHIsMeDSDaZ
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
## Showing image
def draw_circle(event,x,y,flags,param):
    if event==cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img,(x,y),50,color=(0,255,0),-1)
cv2.namedWindow(winname='my_drawing')
cv2.setMouseCallback('my_drawing',draw_circle)


## showing image
img=np.zeros((200,200,3))
while True:
    plt.imshow(img)
    if cv2.waitKey(20) & 0xFF==27:
        break
cv2.destroyAllWindows()